<?php
namespace MyArtJaub\Tests\Webtrees;

use MyArtJaub\Webtrees\Mvc\MvcException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-30 at 12:18:41.
 */
class MvcExceptionTest extends \PHPUnit_Framework_TestCase
{    
    
    /** 
     * @covers MyArtJaub\Webtrees\Mvc\MvcException::__construct
     * @covers MyArtJaub\Webtrees\Mvc\MvcException::getHttpCode
     */
    public function testGetHttpCode()
    {
        //Valid codes
        $this->assertEquals(500, (new MvcException())->getHttpCode());
        $this->assertEquals(200, (new MvcException(200))->getHttpCode());
        $this->assertEquals(404, (new MvcException(404))->getHttpCode());
        $this->assertEquals(500, (new MvcException(500))->getHttpCode());
        
        //Invalid codes
        $this->assertEquals(500, (new MvcException(600))->getHttpCode());
        $this->assertEquals(500, (new MvcException('abc'))->getHttpCode());
    }
    
    /**
     * @covers MyArtJaub\Webtrees\Mvc\MvcException::setHttpCode
     */
    public function testSetHttpCode()
    {
        $ex = new MvcException();        
        $ex->setHttpCode(404);
        
        $this->assertEquals(404, $ex->getHttpCode());
    }
    
    /**
     * @expectedException \InvalidArgumentException
     * @covers MyArtJaub\Webtrees\Mvc\MvcException::setHttpCode
     */
    public function testSetInvalidHttpCode()
    {
        $ex = new MvcException();
        $ex->setHttpCode(600);
    }
    
}
