name: Static analysis PHP

on:
  push:
    branches-ignore:
      - '**-dev'
  pull_request:

jobs:

  phpstan:
    name: phpstan - PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd,intl,mbstring,sqlite,zip
          coverage: none

      - run: composer install --no-progress --ignore-platform-reqs

      - run: composer webtrees-lib:phpstan

  psalm:
    name: psalm - PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']
        
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd,intl,mbstring,sqlite,zip
          coverage: none

      - run: composer global require vimeo/psalm
     
      - run: composer install --no-progress --ignore-platform-reqs
     
      - run: ~/.composer/vendor/bin/psalm
      
      - run: ~/.composer/vendor/bin/psalm --taint-analysis
      